### ISSUE TITLE
scene "isPlayed" property

### ISSUE THREAD

**Issue by Lance798** [keoinn/smorrery-webapp#1]
https://github.com/keoinn/smorrery-webapp/blob/b614ced195b12a56d5519d4bac23c32a8eb2bf10/src/utils/SpaceScene/EmptyScene.js#L15

it should be `this.loop.isPlayed = true`?

**Comment by Lance798** [comment]
or `this.loop.played = 1`

**Comment by keoinn** [comment]
This code segment follows @qavit 's source code. I keep `this.loop.played = 1` because it can represent more than two statuses (Start, Stop, Pause, and so on).

**Comment by Lance798** [comment]
okay, thanks
